export enum PagePathEnum {
  IndexPage = '/',
  MyPage = '/my',
  NotificationPage = '/notice-list',
  WalletPage = '/wallet',
  SettingPage = '/setting',
  RechargeActivityPage = '/recharge-activity',
  WalletDepositNextPage = '/wallet-deposit-next',
  InitialChargePage = '/initial-charge',
  IndexSlotPage = '/slot',
  GameSearchPage = '/game-search',
  GamePage = '/game',
  GameRecordPage = '/game-record',
  PrivacyAgreementPage = '/privacy-agreement',
  TermsOfService = '/terms_of_service',
  CompanyProfilePage = '/company-profile',
  VIPGradePage = '/vip-grade',
  LicensePage = '/license',
  DailySignInPage = '/daily-sign-in',
  DailySingInRecordPage = '/daily-sign-in-record',
  InvitePage = '/invite',
  InviteSettlementRecordPage = '/invite-settlement-record',
  TelegramPage = '/telegram',
  ErrorPage = '/error',
  ActivityHallPage = '/activity',
}
